### ISSUE TITLE
Build is failing on aarch64-linux

### ISSUE THREAD

**Issue by Hellseher** [rwesson/ALFA#29]
Hi,

I happy to announce that your project is packed to Guix and have available substitutions (built
binaries) for the systems:
- x86_64-linux
- i686-linux
- powerpc64le-linux
https://packages.guix.gnu.org/packages/alfa/

However CI was failed on *aarch64-linux* build (system and target)

Ways to reproduce via Guix time machine:
``` shel
guix time-machine --commit=2775bb95c7e4ecfaf81af579e8003dddedab6960 -- build --system=aarch64-linux alfa
...
 22:46:35 : flagging blends
            estimating uncertainties
            H beta detected with flux 4.910E+01 - normalising to 100.0
 23:03:03 : [107] CFITSIO error:          308 bad first element number
            thread            0 , unit           51
make: *** [Makefile:103: fittest] Error 107
...
```
You may use Guix as stand alone system or package manager available from Debian and Ubuntu.

Thanks,
Oleg

**Comment by rwesson** [comment]
Nice to know that ALFA has been packaged for Guix - thanks! I am almost certain that this bug is coming from CFITSIO and not from ALFA itself. I have seen this failure when building for arm64 on launchpad. I see that version 3.49 of CFITSIO is in Guix, so I guess that was used when building ALFA. It is possible that the recently-released version 4.2 might fix this issue, as the changelog mentions ARM architectures. I can't easily test this myself unfortunately.

**Comment by Hellseher** [comment]
Hi,

You are right, with the latest `CFITSIO` library build with Fortrant and Curl added, ALFA passed build on `aarch64-linux` machine! 

```
> ./pre-inst-env guix build --system=aarch64-linux alfa
...
successfully built /gnu/store/pch77m4gi8xi9y0qn6dc15k7jvki8a5g-alfa-2.2.drv
```

**Comment by rwesson** [comment]
That's great to know - thanks for the update, and for the packaging!
